SELECT PACKAGE(*) AS P
FROM Stock_Investments_Half
SUCH THAT
SUM(Price) <= 1000 AND
SUM(Gain) >= 900 WITH PROBABILITY >= 0.97 AND
SUM(Gain) >= 1000 WITH PROBABILITY >= 0.90
MAXIMIZE EXPECTED SUM(Gain)