SELECT Package(*)
FROM GBM_Portfolio_2025 REPEAT 4
WHERE SELL_AFTER <= 10 AND PRICE >= 1.0
SUCH THAT
    COUNT(*) >= 1 AND
    SUM(Price) <= 5000 AND
    EXPECTED SUM(Gain) >= -1000 IN LOWER 0.1 TAIL
MAXIMIZE EXPECTED SUM(Gain)