SELECT Package(*)
FROM Garch_Portfolio_2023 REPEAT 4
WHERE SELL_AFTER <= 10 AND PRICE >= 1.0
SUCH THAT
    COUNT(*) >= 1 AND
    SUM(Price) <= 5000 AND
    EXPECTED SUM(Gain) >= 80
MAXIMIZE EXPECTED SUM(Gain) IN LOWER 0.05 TAIL
